# Generated by Django 3.1.7 on 2021-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0004_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=300),
        ),
    ]
