# Generated by Django 3.1.7 on 2021-11-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0005_auto_20211110_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
